### ISSUE TITLE
polyp分割任务的训练代码train_source没有

### ISSUE THREAD

**Issue by SilverBach805** [Chen-Ziyang/VPTTA#3]
作者您好，感谢你们开源的工作！
有一些问题：我发现你们开源了od/oc分割的训练代码train_source.py，但是息肉分割的训练代码train_source好像没有开源。因为我自己在复现息肉分割数据集的Source Only方法的时候，发现和您论文中表2的Source Only方法相差比较大，大约百分之十左右。您能提供一下这一块的原始的训练代码吗？非常感谢！

**Comment by Chen-Ziyang** [comment]
Hi @SilverBach805 ,
Thanks for your interest.
As mentioned in README, we trained the "Source Only" models following https://github.com/DengPingFan/PraNet, and there are no special changes.
Since we trained the "Source Only" models without other generalization algorithms, it is difficult to obtain robust results due to domain shifts. 
You can attempt to use some generalization algorithms or train the models following the leave-one-domain-out strategy (e.g., train the model on Domain A-C and test it on Domain D) to obtain more generalized models. 
We hope these suggestions are helpful to you.

**Comment by SilverBach805** [comment]
Alright, thank you for the response! I'll go and implement it following the link you provided. Also, thanks for the various suggestions you've given!
